[tool.poetry]
name = "VM2205"
version = "0.1.0"
description = ""
authors = ["x <x@read.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
